name: Autograde Solidity Assignment
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    - name: Install dependencies
      run: |
        npm install --save-dev hardhat
        npm install --save-dev "hardhat@^2.22.12" "@nomicfoundation/hardhat-toolbox@^5.0.0"
    - name: Autograding
      id: autograding
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Autograding
        command: npx hardhat test
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        AUTOGRADE_RESULTS: "${{steps.autograding.outputs.result}}"
      with:
        runners: autograding