name: Autograde Solidity Assignment
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    - name: Install dependencies
      run: |
        npm install --save-dev hardhat
        npm install --save-dev "hardhat@^2.22.12" "@nomicfoundation/hardhat-toolbox@^5.0.0"
    - name: Autograding
      id: autograding
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Autograding
        setup-command: ''
        command: npx hardhat test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        AUTOGRADING: "${{steps.autograding.outputs.result}}"
      with:
        runners: autograding
